"""
Signal Engine for Polymarket 5-Minute BTC Binary Options

Implements the v3 composite momentum signal generation with 10-minute trend filtering.
Based on research by Jung-Hua Liu (March 2026).

Key innovations from paper:
1. Multi-timeframe momentum analysis (30s/60s/120s/240s)
2. 10-minute trend filter to eliminate directional bias
3. DISLOCATION, DIRECTIONAL, and MAKER signal types
4. Fractional Kelly position sizing with quarter-Kelly cap
"""

from dataclasses import dataclass
from enum import Enum
from typing import Optional
import numpy as np
import logging

logger = logging.getLogger(__name__)


class SignalType(Enum):
    """Types of trading signals."""
    DISLOCATION = "dislocation"  # Primary: BTC moved but token hasn't adjusted
    DIRECTIONAL = "directional"  # Secondary: Final 30s momentum confirmation
    MAKER = "maker"  # Tertiary: Earn maker rebate
    NO_SIGNAL = "no_signal"  # No trade


class Direction(Enum):
    """Trade direction."""
    UP = "up"
    DOWN = "down"
    NONE = "none"


@dataclass
class MomentumReading:
    """Momentum data at a single timeframe."""
    timeframe_seconds: int
    slope: float
    normalized_slope: float
    weight: float


@dataclass
class CompositeSignal:
    """Complete signal generated by the engine."""
    signal_type: SignalType
    direction: Direction
    confidence: float
    fair_prob: float
    edge: float
    fee_adjusted_edge: float
    momentum_readings: list[MomentumReading]
    trend_direction: Direction
    trend_strength: float
    window_time_remaining: int
    btc_current_price: float
    btc_window_open_price: float
    btc_price_change_pct: float
    token_price: float
    reasoning: str


class SignalEngine:
    """
    Multi-timeframe momentum signal generator for Polymarket 5-min BTC binaries.

    Implements v3 momentum weights that favor longer lookbacks to reduce noise
    sensitivity and eliminate the directional bias that caused 80% of v2 trades
    to bet UP during DOWN-trending markets.
    """

    def __init__(
        self,
        momentum_weights: dict[int, float] = None,
        trend_window_seconds: int = 600,
        dislocation_btc_move_min: float = 0.0005,
        dislocation_confidence_min: float = 0.45,
        directional_confidence_min: float = 0.45,
        maker_confidence_min: float = 0.45,
        fair_prob_capped: float = 0.80,
        fair_prob_time_decay_factor: float = 5.0,
        directional_final_seconds: int = 30,
        btc_move_noise_threshold: float = 0.0003,
        noise_time_remaining: int = 90,
    ):
        """
        Initialize the signal engine with configurable parameters.

        Args:
            momentum_weights: Dict mapping timeframe (seconds) to weight.
                             Default v3: {30: 0.20, 60: 0.30, 120: 0.35, 240: 0.15}
            trend_window_seconds: Window for medium-term trend calculation (default 600s = 10min)
            dislocation_btc_move_min: Minimum BTC move % to trigger DISLOCATION (0.05%)
            dislocation_confidence_min: Min confidence for DISLOCATION signals
            directional_confidence_min: Min confidence for DIRECTIONAL signals
            maker_confidence_min: Min confidence for MAKER signals
            fair_prob_capped: Maximum fair probability estimate (0.80)
            fair_prob_time_decay_factor: Factor for fair prob calculation
            directional_final_seconds: Only fire DIRECTIONAL in final N seconds
            btc_move_noise_threshold: BTC move below this = noise (0.03%)
            noise_time_remaining: Reject if >N seconds remaining and BTC move is noise
        """
        # Default v3 weights (favor longer lookbacks to reduce noise)
        self.momentum_weights = momentum_weights or {30: 0.20, 60: 0.30, 120: 0.35, 240: 0.15}
        self.trend_window_seconds = trend_window_seconds
        self.dislocation_btc_move_min = dislocation_btc_move_min
        self.dislocation_confidence_min = dislocation_confidence_min
        self.directional_confidence_min = directional_confidence_min
        self.maker_confidence_min = maker_confidence_min
        self.fair_prob_capped = fair_prob_capped
        self.fair_prob_time_decay_factor = fair_prob_time_decay_factor
        self.directional_final_seconds = directional_final_seconds
        self.btc_move_noise_threshold = btc_move_noise_threshold
        self.noise_time_remaining = noise_time_remaining

        # Validate weights sum to 1.0
        total_weight = sum(self.momentum_weights.values())
        if abs(total_weight - 1.0) > 0.001:
            logger.warning(f"Momentum weights sum to {total_weight}, normalizing to 1.0")
            self.momentum_weights = {
                k: v / total_weight for k, v in self.momentum_weights.items()
            }

        logger.info(f"SignalEngine initialized with weights: {self.momentum_weights}")

    def compute_slope(self, prices: np.ndarray) -> float:
        """
        Compute linear regression slope over price series.

        Uses ordinary least squares to find the best-fit line slope.
        This represents the trend direction and magnitude.

        Args:
            prices: Array of price values

        Returns:
            Slope in price units per unit time
        """
        if len(prices) < 2:
            return 0.0

        n = len(prices)
        x = np.arange(n)
        x_mean = x.mean()
        y_mean = prices.mean()

        # Numerator: Σ(x - x_mean)(y - y_mean)
        numerator = np.sum((x - x_mean) * (prices - y_mean))
        # Denominator: Σ(x - x_mean)²
        denominator = np.sum((x - x_mean) ** 2)

        if denominator == 0:
            return 0.0

        slope = numerator / denominator
        return slope

    def compute_momentum_readings(
        self,
        price_buffers: dict[int, list[float]],
        current_price: float,
    ) -> tuple[list[MomentumReading], float, Direction]:
        """
        Compute momentum at multiple timeframes and combine into composite signal.

        Args:
            price_buffers: Dict mapping timeframe -> list of recent prices
            current_price: Current BTC price

        Returns:
            Tuple of (momentum readings, composite confidence, composite direction)
        """
        readings = []
        weighted_slope = 0.0

        for tf, weight in self.momentum_weights.items():
            if tf not in price_buffers or len(price_buffers[tf]) < 2:
                continue

            # Extract prices if buffer contains tuples (timestamp, price)
            raw = price_buffers[tf]
            if isinstance(raw[0], tuple):
                prices = np.array([p for _, p in raw])
            else:
                prices = np.array(raw)
            slope = self.compute_slope(prices)

            # Normalize slope by mean price to make comparable across timeframes
            mean_price = prices.mean()
            normalized_slope = slope / mean_price if mean_price > 0 else 0.0

            reading = MomentumReading(
                timeframe_seconds=tf,
                slope=slope,
                normalized_slope=normalized_slope,
                weight=weight,
            )
            readings.append(reading)

            # Add to weighted composite
            weighted_slope += normalized_slope * weight

        # Determine direction from composite slope
        if weighted_slope > 0:
            direction = Direction.UP
        elif weighted_slope < 0:
            direction = Direction.DOWN
        else:
            direction = Direction.NONE

        # Confidence is absolute value of weighted slope (scaled for BTC-scale prices)
        # weighted_slope is normalized slope (~0.001 for 0.1% move in BTC)
        # Scale up: multiply by 1000 to get meaningful confidence (0-1 range)
        # BTC-scale: 0.001 normalized slope ≈ 0.1% move should give ~0.5 confidence
        confidence = min(abs(weighted_slope) * 1000, 1.0)

        return readings, confidence, direction

    def compute_trend(
        self,
        trend_prices: list,
    ) -> tuple[Direction, float]:
        """
        Compute medium-term trend over 10-minute window.

        Args:
            trend_prices: List of prices over trend window

        Returns:
            Tuple of (trend direction, trend strength)
        """
        if len(trend_prices) < 2:
            return Direction.NONE, 0.0

        # Extract prices if list contains tuples (timestamp, price)
        if isinstance(trend_prices[0], tuple):
            prices = np.array([p for _, p in trend_prices])
        else:
            prices = np.array(trend_prices)
        slope = self.compute_slope(prices)
        mean_price = prices.mean()
        normalized_slope = slope / mean_price if mean_price > 0 else 0.0

        if normalized_slope > 0:
            direction = Direction.UP
        elif normalized_slope < 0:
            direction = Direction.DOWN
        else:
            direction = Direction.NONE

        strength = abs(normalized_slope)
        return direction, strength

    def compute_fair_probability(
        self,
        btc_price_change_pct: float,
        time_remaining: int,
    ) -> float:
        """
        Estimate fair probability based on BTC price movement.

        From paper:
        fair_prob = 0.5 + (|Δ_btc| / time_decay) × 5.0, capped at 0.80

        Args:
            btc_price_change_pct: Absolute BTC price change percentage
            time_remaining: Seconds remaining in window

        Returns:
            Estimated fair probability (0.5 to 0.80)
        """
        # Time decay: larger moves earlier in window = more significant
        # Smaller time remaining = move has less time to reverse
        time_factor = 1.0 - (time_remaining / 300)  # Normalize to 5-min window
        time_decay = max(time_factor, 0.1)  # Avoid division by zero

        raw_prob = 0.5 + (abs(btc_price_change_pct) / time_decay) * self.fair_prob_time_decay_factor

        # Cap at reasonable maximum
        fair_prob = min(raw_prob, self.fair_prob_capped)
        return fair_prob

    def check_dislocation(
        self,
        btc_price_change_pct: float,
        current_token_price: float,
        token_has_adjusted: bool,
        confidence: float,
        trend_agrees: bool,
        edge_threshold: float = 0.02,
    ) -> tuple[bool, float, float]:
        """
        Check if DISLOCATION signal conditions are met.

        DISLOCATION fires when:
        1. BTC has moved >0.05% in current window
        2. Polymarket token price hasn't adjusted
        3. Fee-adjusted edge >2%
        4. 10-min trend agrees

        Args:
            btc_price_change_pct: Absolute BTC price change percentage
            current_token_price: Current Polymarket token price
            token_has_adjusted: Whether token price reflects BTC move
            confidence: Composite momentum confidence
            trend_agrees: Whether signal aligns with 10-min trend
            edge_threshold: Minimum edge required (default 2%)

        Returns:
            Tuple of (signal_valid, fair_prob, edge)
        """
        if token_has_adjusted:
            return False, 0.0, 0.0

        if abs(btc_price_change_pct) < self.dislocation_btc_move_min:
            return False, 0.0, 0.0

        if confidence < self.dislocation_confidence_min:
            return False, 0.0, 0.0

        # Estimate time remaining (assuming 5-min windows)
        time_remaining = 300  # Default full window
        fair_prob = self.compute_fair_probability(btc_price_change_pct, time_remaining)

        # Edge = fair_prob - current_price
        edge = fair_prob - current_token_price

        # Fee-adjusted edge (subtract ~1.56% fee at $0.50)
        fee_adjustment = current_token_price * 0.0312  # ~3% total (fee + slippage)
        fee_adjusted_edge = edge - fee_adjustment

        if fee_adjusted_edge < edge_threshold:
            return False, fair_prob, edge

        if not trend_agrees:
            return False, fair_prob, edge

        return True, fair_prob, edge

    def check_directional(
        self,
        confidence: float,
        btc_confirms: bool,
        trend_agrees: bool,
        time_remaining: int,
    ) -> bool:
        """
        Check if DIRECTIONAL signal conditions are met.

        DIRECTIONAL fires in final 30 seconds when:
        1. Composite confidence >= 0.45
        2. BTC price confirms direction by >0.03%
        3. 10-min trend agrees

        Args:
            confidence: Composite momentum confidence
            btc_confirms: Whether BTC move >0.03% in signal direction
            trend_agrees: Whether signal aligns with 10-min trend
            time_remaining: Seconds remaining in window

        Returns:
            True if DIRECTIONAL signal is valid
        """
        if time_remaining > self.directional_final_seconds:
            return False

        if confidence < self.directional_confidence_min:
            return False

        if not btc_confirms:
            return False

        if not trend_agrees:
            return False

        return True

    def check_maker(
        self,
        confidence: float,
        trend_agrees: bool,
    ) -> bool:
        """
        Check if MAKER signal conditions are met.

        MAKER posts limit orders 2 cents below ask to earn 20% maker rebate.
        Requires confidence >= 0.45 and trend agreement.

        Args:
            confidence: Composite momentum confidence
            trend_agrees: Whether signal aligns with 10-min trend

        Returns:
            True if MAKER signal is valid
        """
        if confidence < self.maker_confidence_min:
            return False

        if not trend_agrees:
            return False

        return True

    def filter_noise(
        self,
        btc_price_change_pct: float,
        time_remaining: int,
    ) -> bool:
        """
        Filter out noise signals.

        Rule: BTC move <0.03% with >90s remaining is noise -> reject.

        Args:
            btc_price_change_pct: Absolute BTC price change percentage
            time_remaining: Seconds remaining in window

        Returns:
            True if signal is noise (should reject)
        """
        is_noise = (
            abs(btc_price_change_pct) < self.btc_move_noise_threshold
            and time_remaining > self.noise_time_remaining
        )
        return is_noise

    def generate_signal(
        self,
        price_buffers: dict[int, list[float]],
        trend_prices: list[float],
        current_price: float,
        window_open_price: float,
        current_token_price: float,
        token_has_adjusted: bool,
        window_time_remaining: int,
    ) -> CompositeSignal:
        """
        Generate complete trading signal from market data.

        This is the main entry point for signal generation. It:
        1. Computes multi-timeframe momentum
        2. Computes 10-minute trend
        3. Evaluates DISLOCATION, DIRECTIONAL, and MAKER signals
        4. Applies noise filtering

        Args:
            price_buffers: Dict of {timeframe: list of recent prices}
            trend_prices: List of prices over 10-minute window
            current_price: Current BTC/USD price
            window_open_price: BTC price at window open
            current_token_price: Current Polymarket UP token price
            token_has_adjusted: Whether token price reflects BTC move
            window_time_remaining: Seconds until window closes

        Returns:
            CompositeSignal with all details or NO_SIGNAL if no valid signal
        """
        # Compute momentum
        readings, confidence, direction = self.compute_momentum_readings(
            price_buffers, current_price
        )

        # Compute trend
        trend_direction, trend_strength = self.compute_trend(trend_prices)

        # BTC price change
        btc_change_pct = (current_price - window_open_price) / window_open_price

        # Check if signal aligns with trend
        trend_agrees = (direction == trend_direction) or (direction == Direction.NONE)

        # Check for noise
        if self.filter_noise(btc_change_pct, window_time_remaining):
            return CompositeSignal(
                signal_type=SignalType.NO_SIGNAL,
                direction=Direction.NONE,
                confidence=0.0,
                fair_prob=0.0,
                edge=0.0,
                fee_adjusted_edge=0.0,
                momentum_readings=readings,
                trend_direction=trend_direction,
                trend_strength=trend_strength,
                window_time_remaining=window_time_remaining,
                btc_current_price=current_price,
                btc_window_open_price=window_open_price,
                btc_price_change_pct=btc_change_pct,
                token_price=current_token_price,
                reasoning="Signal rejected: noise",
            )

        # Check DISLOCATION (primary signal)
        disl_valid, fair_prob, edge = self.check_dislocation(
            btc_change_pct,
            current_token_price,
            token_has_adjusted,
            confidence,
            trend_agrees,
        )

        if disl_valid:
            fee_adj_edge = edge - (current_token_price * 0.0312)
            return CompositeSignal(
                signal_type=SignalType.DISLOCATION,
                direction=direction,
                confidence=confidence,
                fair_prob=fair_prob,
                edge=edge,
                fee_adjusted_edge=fee_adj_edge,
                momentum_readings=readings,
                trend_direction=trend_direction,
                trend_strength=trend_strength,
                window_time_remaining=window_time_remaining,
                btc_current_price=current_price,
                btc_window_open_price=window_open_price,
                btc_price_change_pct=btc_change_pct,
                token_price=current_token_price,
                reasoning=f"DISLOCATION: BTC moved {btc_change_pct:.4%}, token lagging",
            )

        # Check DIRECTIONAL (secondary signal)
        btc_confirms = abs(btc_change_pct) > 0.0003  # 0.03%
        if self.check_directional(confidence, btc_confirms, trend_agrees, window_time_remaining):
            return CompositeSignal(
                signal_type=SignalType.DIRECTIONAL,
                direction=direction,
                confidence=confidence,
                fair_prob=0.5 + confidence,
                edge=confidence - current_token_price if direction == Direction.UP else current_token_price - confidence,
                fee_adjusted_edge=0.0,
                momentum_readings=readings,
                trend_direction=trend_direction,
                trend_strength=trend_strength,
                window_time_remaining=window_time_remaining,
                btc_current_price=current_price,
                btc_window_open_price=window_open_price,
                btc_price_change_pct=btc_change_pct,
                token_price=current_token_price,
                reasoning=f"DIRECTIONAL: Final {window_time_remaining}s, confidence {confidence:.2f}",
            )

        # Check MAKER (tertiary signal)
        if self.check_maker(confidence, trend_agrees):
            return CompositeSignal(
                signal_type=SignalType.MAKER,
                direction=direction,
                confidence=confidence,
                fair_prob=0.5,
                edge=0.0,  # MAKER earns spread, not directional edge
                fee_adjusted_edge=0.0,
                momentum_readings=readings,
                trend_direction=trend_direction,
                trend_strength=trend_strength,
                window_time_remaining=window_time_remaining,
                btc_current_price=current_price,
                btc_window_open_price=window_open_price,
                btc_price_change_pct=btc_change_pct,
                token_price=current_token_price,
                reasoning=f"MAKER: Earn {0.20:.0%} maker rebate, confidence {confidence:.2f}",
            )

        # No signal
        return CompositeSignal(
            signal_type=SignalType.NO_SIGNAL,
            direction=Direction.NONE,
            confidence=0.0,
            fair_prob=0.0,
            edge=0.0,
            fee_adjusted_edge=0.0,
            momentum_readings=readings,
            trend_direction=trend_direction,
            trend_strength=trend_strength,
            window_time_remaining=window_time_remaining,
            btc_current_price=current_price,
            btc_window_open_price=window_open_price,
            btc_price_change_pct=btc_change_pct,
            token_price=current_token_price,
            reasoning="No signal met criteria",
        )


# =============================================================================
# LLM Filter (Placeholder)
# =============================================================================

class LLMFilter:
    """
    LLM-augmented trade filter using structured prompts.

    From paper: OpenClaw implements hybrid human-AI architecture where
    an LLM serves as decision-making co-pilot rather than standalone agent.

    5-section briefing format:
    1. BTC Trend - Current price, 5-min window change, momentum slopes, RSI, VWAP
    2. Recent Outcomes - Last 8 resolved trades with direction → WIN/LOSS
    3. Portfolio - Cash balance, session P&L, win rate, consecutive losses
    4. Market - Window slug, time remaining, token prices, existing bets
    5. Signal - Type, direction, confidence, edge, trend alignment
    """

    def __init__(
        self,
        model: str = "kimi",
        temperature: float = 0.3,
        timeout_seconds: int = 10,
        fail_to_reject: bool = True,
    ):
        self.model = model
        self.temperature = temperature
        self.timeout_seconds = timeout_seconds
        self.fail_to_reject = fail_to_reject

    def build_prompt(
        self,
        signal: CompositeSignal,
        recent_outcomes: list[tuple[str, bool]],
        portfolio: dict,
    ) -> str:
        """
        Build structured 5-section briefing prompt for LLM.

        Args:
            signal: The signal to evaluate
            recent_outcomes: List of (direction, win) tuples for last 8 trades
            portfolio: Dict with cash_balance, session_pnl, win_rate, consecutive_losses

        Returns:
            Formatted prompt string
        """
        # Format recent outcomes
        outcomes_str = "\n".join(
            f"  - {dir_} → {'WIN' if win else 'LOSS'}"
            for dir_, win in recent_outcomes[-8:]
        )

        prompt = f"""You are a risk management co-pilot for a Polymarket 5-minute BTC binary trading system.

## 1. BTC Trend
- Current Price: ${signal.btc_current_price:,.2f}
- Window Open Price: ${signal.btc_window_open_price:,.2f}
- Price Change: {signal.btc_price_change_pct:+.4%}
- 10-Minute Trend: {signal.trend_direction.value.upper()} (strength: {signal.trend_strength:.6f})
- Confidence: {signal.confidence:.4f}

## 2. Recent Outcomes
{outcomes_str or '  (No recent trades)'}

## 3. Portfolio
- Cash Balance: ${portfolio.get('cash_balance', 0):.2f}
- Session P&L: ${portfolio.get('session_pnl', 0):.2f}
- Win Rate: {portfolio.get('win_rate', 0):.1%}
- Consecutive Losses: {portfolio.get('consecutive_losses', 0)}

## 4. Market
- Signal Type: {signal.signal_type.value.upper()}
- Direction: {signal.direction.value.upper()}
- Time Remaining: {signal.window_time_remaining}s
- Token Price: ${signal.token_price:.4f}
- Fair Prob: {signal.fair_prob:.4f}
- Edge: {signal.edge:.4f}
- Fee-Adjusted Edge: {signal.fee_adjusted_edge:.4f}

## 5. Signal Assessment
{signal.reasoning}

## Hard Rules
- No duplicate bets on same 5-minute window
- Reject signals opposing 15-minute trend (unless BTC move >0.10%)
- After 3+ consecutive losses, require edge >0.05
- BTC move <0.03% with >90s remaining = noise → reject
- Don't bet against side priced >60% without strong evidence
- Cash <30% starting → only high-conviction trades

DECISION: Should this signal be APPROVED or REJECTED?
Provide your decision and brief reasoning."""
        return prompt

    def filter_signal(
        self,
        signal: CompositeSignal,
        recent_outcomes: list[tuple[str, bool]],
        portfolio: dict,
    ) -> tuple[bool, str]:
        """
        Filter signal using LLM judgment.

        Args:
            signal: Signal to filter
            recent_outcomes: Recent trade outcomes
            portfolio: Portfolio state

        Returns:
            Tuple of (approved, reasoning)
        """
        # In production, this would call the LLM API
        # For now, implement basic hard rules
        prompt = self.build_prompt(signal, recent_outcomes, portfolio)

        # Basic hard rule checks
        if portfolio.get('consecutive_losses', 0) >= 3:
            if signal.edge < 0.05:
                return False, "REJECT: 3+ consecutive losses + edge < 5%"

        cash_pct = portfolio.get('cash_balance', 0) / max(portfolio.get('starting_balance', 1000), 1)
        if cash_pct < 0.30:
            if signal.confidence < 0.6:
                return False, "REJECT: Cash <30% + low confidence"

        # High-priced side rule
        if signal.token_price > 0.60 and signal.edge < 0.10:
            return False, "REJECT: Don't fight high-priced side without strong edge"

        # All checks passed
        return True, "APPROVED: Signal passes all hard rules"

    def filter_signal_llm(
        self,
        signal: CompositeSignal,
        recent_outcomes: list[tuple[str, bool]],
        portfolio: dict,
    ) -> tuple[bool, str]:
        """
        Filter signal using actual LLM call.

        This is the production version that calls the LLM API.
        Currently a placeholder - integrate with actual LLM provider.

        Args:
            signal: Signal to filter
            recent_outcomes: Recent trade outcomes
            portfolio: Portfolio state

        Returns:
            Tuple of (approved, reasoning from LLM)
        """
        # Placeholder - in production, call actual LLM
        # For now, fall back to basic filtering
        if self.fail_to_reject:
            return False, "LLM unavailable: default REJECT"

        return self.filter_signal(signal, recent_outcomes, portfolio)
